version: "3"	#docker version 3 사용
services: 	#service들 정의
  database: 	#service 이름
    image: mysql	#불러올 image
    container_name: mysql_db 	#container 이름 지정
    environment:	# 환경 설정
      - MYSQL_DATABASE=mysql_db
      - MYSQL_ROOT_HOST={MYSQL_ROOT_HOST}
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
    ports:		#port 지정
      - 3306:3306
    volumes:	#볼륨 지정
      - mysql:/var/lib/mysql/
    networks:		#사용할 네트워크 지정
      - hello_spring_network_02
  webapp:
    build:		#image를 DockerFile 기반으로 사용한다
      context: ../
      dockerfile: Dockerfile    #기존에 설정해둔 DockerFile을 지정히여 build 된 jar 파일을 container에 올린다.
    restart: always		#컨테이너 재실행
    depends_on:		#database service가 실행된 이후에 실행
      - database
    ports:
      - 9090:9090
    container_name: hello-spring
    environment:	#환경 설정(database연결 및 profile 지정)
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/mysql_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME={MYSQL_ROOT_HOST}
      - SPRING_DATASOURCE_PASSWORD={MYSQL_ROOT_PASSWORD}
      - SPRING_PROFILES_ACTIVE=local		#사용할 profile 지정
    networks:
      - hello_spring_network_02

networks:	#네트워크 설정
  hello_spring_network_02:
volumes:
  mysql: {}